### PR TITLE
(#68) Inline validation for form fields.

### PR DESCRIPTION
**Pull request by waseem**
Submit button is disabled in case there is a validation error.

### CODE REVIEW

**Comment by dira** [comment]
@waseem Looks good, but I think it should be complemented by having the same validations on the server side.

**Comment by waseem** [comment]
@dira Yes, sure. I'll write them as well. Here comes carpal tunnel syndrome. :D

**Comment by dira** [comment]
auto insurance: `company_name` was validated in view, not in model
bank account: had validations ofr `account_username` and `account_password` that are not shown (the schema gas access_code that is not required)
credit_beaureau: `company_name` was validated in view, not in model
deposit_box: `box_number` and `key_location` were validated in view, not in model

**Comment by dira** [comment]
@waseem Heh, I hear you :)

**Comment by dira** [comment]
@waseem Please take a look at the last commit - I refactored the form validations to take into account what's defined in the schema. While checking that it doesn't miss something, I found the following:

* auto insurance: `company_name` was validated in view, not in model
* bank account: had validations ofr `account_username` and `account_password` that are not shown (the schema has access_code that is not required)
* credit_bureau: `company_name` was validated in view, not in model
* deposit_box: `box_number` and `key_location` were validated in view, not in model
* storage unit: `company_name` was validated in view, not in model

**Comment by waseem** [comment]
@dira Those changes definitely look good. Thanks a bunch!

**Comment by waseem** [comment]
@dira I added validations to Rails models. Please have a look.

**Comment by whitmanc** [comment]
@waseem Yes, it looks like the new document has a section called "Auto Registration", which is misspelled in the document as "AUTO REGISTRAION" - looks like it was renamed in the document.

**Comment by waseem** [comment]
I have moved creation of Auto Registration model along with its validation to #69

**Comment by whitmanc** [comment]
@waseem this is great, here is feedback:

Everything looks fine in regards to how the in-line validations behave, but there were some forms I was not able to test as it wasn't possible to create records for them. Please see below for a precise list of forms that records could not be created for. Note that this was a fresh database.

* __Section  3 - Prenuptials, etc__
  * Funeral Planning
* __Section 4 - Assets__
  * Can't create a Bank Account record - no js console error 
  * Real Property
  * Business Holding
  * Other Investment 
  * Pension Survivorship  Plan
  * Military Benefit 
  * Foreign Holding
* __Section 5 - Liabilities__
  * Note: not sure if it's coincidence, but none of the forms in this particular section were able to create new records
  * Student Loans
  * Credit Card
  * Mortgages
  * Utilities & Recurring Bills
  * Auto Insurance
  * Home Insurance
  * Other Outstanding Debt
* __Section 6 - Online/offline footprint__
  * Professional Accounts
  * Club Memberships
  * Airline Memberships
  * Driver's License/Auto Registration
  * Safe Boxes
  * Storage Units
  * Passports
  * Fraud protection
  * Credit Bureaus
  * Physical Mail
  * Firearm Registration

**Comment by whitmanc** [comment]
NOTE: tests still broken & need to be fixed

**Pull request closed without merging**
