### PR TITLE
69 model fields

### PR DESCRIPTION
**Pull request by dira**

### CODE REVIEW

**Comment by dira** [comment]
Created a PR to have a place to talk about the code.

So, I made the form view `render` (it needed to be invoked on the `Form` view) and cleaned up the code.

I think the next step is to figure out how to submit the form, with all the fields, through the AJAX form submission of the `fileupload` plugin http://blueimp.github.io/jQuery-File-Upload/basic.html

@waseem , I'm passing the issue back to you, but feel free to ping me if you need more help on this one

**Comment by waseem** [comment]
@dira So I tried to use Ajax to POST/PUT additional parameters with jquery fileupload plugin but it was really pain and I was not able to do it. I instead ended up using [backbone-model-file-upload](https://github.com/homeslicesolutions/backbone-model-file-upload) plugin. And it made uploading files with Backbone really painless. Please see my last commit.

I however ended up writing something like [this](https://github.com/accelestate/accelestate/commit/49a002fc3ea224fb55a92b5ac6c855966d41c576#diff-8407c85d98e9af5c87fa22ae06b1d721R34) because somehow form submission sends form data without a top level parameter key named `death_confirmation`. This, however, is not caused by the plugin but something else, probably the way edit form is now. Can you please lend me a hand with it?

**Comment by dira** [comment]
@waseem 

Cool being able to make it work with this plugin. I think the next step is to remove `EditDeathConfirmationFormView`, since it can be integrated in `EditDeathConfirmationView`.

After some debugging, I found out that it is the plugin that strips the `death_confirmation` container in the json. Even more, the json contains `death_confirmation` if the user hasn't selected a file, and does not contain it when a file is present.

This is because the plugin overrides Backbone's `save` method. The original method delegates to `Backbone.sync`, which calls `toJSON` to get the attributes hash. The plugin does not call `toJSON` and serializes the attributes itself.

Trying to patch it fast now - if I don't manage, I'll pass the PR back to you :D

**Comment by dira** [comment]
@waseem pushed a patch. 

Remanining things to do: 
* make the timestamp field work properly
* on edit - show the link to the document (if it exists)

**Comment by whitmanc** [comment]
@waseem Has the `AirlineMembership` been removed in this PR, or will it be? If not, would it be possible to open an issue for it  (marked for milestone 2.1) - it needs to be removed per new spec

**Comment by waseem** [comment]
@whitmanc No, the `AirlineMembership` is still in the codebase. I've created #84 for it.

**Pull request merged**
